### PR TITLE
CountDownTimer

### PR DESCRIPTION
**Pull request by yellurividyendra**
Dear Reviewer,

I hope this message finds you well. I have submitted a pull request,
This pull request adds the CountDownTimer Feature using Kotlin. This feature in the app  contains the three buttons like Start, Pause , Reset .

Thank you for your time and consideration.
Best regards,
[Yelluri Vidyendra]
[[iit2022057@iiitl.ac.in]

### CODE REVIEW

**Comment by AkshayPratapSingh09** [comment]
Both of the Folder are un-accessible fix it

**Comment by yellurividyendra** [comment]
> Both of the Folder are un-accessible fix it

I regret any misunderstanding that may have occurred. Allow me to clarify my point more explicitly for your better understanding. If there are specific aspects you find unclear, please feel free to ask, and I will be more than happy to provide further assistance. Thank you for your understanding and patience.

**Comment by AkshayPratapSingh09** [comment]
Not accessbile

Might be working at your local machine but not getting tracked by git, might be a git conflict, more than 1 folder has git in it or  maybe carrying large files(more than 100mb)

**Comment by yellurividyendra** [comment]
> Not accessbile
> 
> Might be working at your local machine but not getting tracked by git, might be a git conflict, more than 1 folder has git in it or maybe carrying large files(more than 100mb)



i understood the problem sir,
give me some time i will make the changes As Soon As Possible :)

**Comment by yellurividyendra** [comment]
@AkshayPratapSingh09 

fixed the issue, now its ready to merge
thank you for your time and consideration:)

**Comment by AkshayPratapSingh09** [comment]
Missing <Username>.md in Contributors directory

**Comment by yellurividyendra** [comment]
> Missing .md in Contributors directory

@AkshayPratapSingh09 
Done sir , once check it
Now its ready to merge;)

**Pull request closed without merging**
