### PR TITLE
TextToSpeech

### PR DESCRIPTION
**Pull request by yellurividyendra**
Dear Reviewer,

I hope this message finds you well. I have submitted a pull request,
I am pleased to submit this pull request that introduces a Text-to-Speech (TTS) feature to the app, enhancing its functionality and accessibility. This significant improvement allows users to convert written text into spoken words, making the content audible and accessible to a wider audience.

Thank you for your time and consideration.
Best regards,
[Yelluri Vidyendra]
[[iit2022057@iiitl.ac.in]

### CODE REVIEW

**Comment by AkshayPratapSingh09** [comment]
Also Add Contribtor.md for yourself

**Comment by yellurividyendra** [comment]
> Also Add Contribtor.md for yourself

@AkshayPratapSingh09  Sure sir

**Comment by AkshayPratapSingh09** [comment]
Not accessbile

Still folders are not accessible and no Contribution.md file added in  Contributors directory

**Comment by yellurividyendra** [comment]
@yellurividyendra 

fixed the issue, now its ready to merge 
thank you for your time and consideration:)

**Pull request closed without merging**
